version: 2

project_name: test-hybrid-release

# Pas de build pour le bundle-only release
builds:
  - skip: true

# Configuration de la release GitHub
release:
  github:
    owner: loicsikidi
    name: test-hybrid-release
  draft: false
  prerelease: false
  mode: append
  extra_files:
    - glob: ./output/tpm-ca-certificates.pem
    - glob: ./output/checksums.txt
    - glob: ./output/checksums.txt.sigstore.json
  header: |
    ## TPM Trust Bundle {{ .Tag }}

    ### What's Changed

    This release contains the TPM Trust Bundle generated at commit `{{ .FullCommit }}`.

    ### Artifacts

    - **`tpm-ca-certificates.pem`** - The TPM trust bundle
    - **`checksums.txt`** - SHA-256 checksum
    - **`checksums.txt.sigstore.json`** - Cosign v3 signature bundle

    ### Verification

    #### Option 1: GitHub CLI (simplest)
    ```bash
    gh attestation verify tpm-ca-certificates.pem --owner loicsikidi
    ```

    #### Option 2: Cosign

    > [!TIP]
    > Make sure to you have Cosign **v3** installed!
  
    ```bash
    cosign verify-blob \
      --bundle checksums.txt.sigstore.json \
      --certificate-identity-regexp 'https://github.com/loicsikidi/test-hybrid-release/{{ .Tag }}' \
      --certificate-oidc-issuer https://token.actions.githubusercontent.com \
      checksums.txt
    ```

    #### Option 3: Reproducibility
    ```bash
    git clone https://github.com/loicsikidi/test-hybrid-release
    cd test-hybrid-release
    git checkout {{ .Tag }}
    go run ./cmd/main.go generate
    sha256sum tpm-ca-certificates.pem  # Compare with checksums.txt
    ```
  footer: |
    **Generated with GoReleaser 🚀**

# Changelog
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'
